### PR TITLE
Adding openssl 1.0.2

### PR DESCRIPTION
**Pull request by abenbachir**

### CODE REVIEW

**Comment by abenbachir** [comment]
@jeffaco can you merge this.

**Comment by jeffaco** [comment]
I don't fully understand why this change is needed at all. I don't think it should be, please explain your rational.

The point of `ostc-openssl` is to deal with binary compatibility differences between various releases of OpenSSL. From the [OpenSSL FAQ](https://www.openssl.org/docs/faq.html#PROG):

>How does the versioning scheme work?
>
>After the release of OpenSSL 1.0.0 the versioning scheme changed. Letter releases (e.g. 1.0.1a) can only contain bug and security fixes and no new features. Minor releases change the last number (e.g. 1.0.2) and can contain new features that retain binary compatibility. Changes to the middle number are considered major releases and neither source nor binary compatibility is guaranteed.

Thus, you'll note that this repository contains OpenSSL 1.0.0 and OpenSSL 1.1.0. The intent is to build against a stable version of SSL (for binary compatibility purposes), then at install time utilize the version of SSL currently installed on the system. Indeed, for a variety of reasons, Microsoft generally never installs SSL, but instead depends on the version of SSL currently installed on the system. There are compelling reasons for this, and I don't suggest you deviate from it.

Products that use this will ship with multiple versions of SSL binaries, then install the proper binaries at installation time and resolve via soft linkages to the version that is installed on the system. So, for example, if the system had OpenSSL 1.0.2 installed, we'd use the binaries linked against OpenSSL 1.0.0. That would work.

Finally, while I'm happy to commit something here that makes sense, I am on a different team now. You should probably work through the IDC (or perhaps OMI development) for taking patches here. But in general, this should be automatically maintained as dependent products need support for newer versions of SSL (i.e. 1.2.x, 2.x, etc).

Follow-on questions can be here or via corporate E-Mail. If you want to schedule a brief meeting to discuss, I can do that too.

**Comment by abenbachir** [comment]
@jeffaco for OMSAgent project we will upgrade from SSL 1.0.0 to 1.0.2. Because Ruby 2.6 require at least SSL 1.0.1.

We don't use this project anymore to build OMSAgent, We just want to add SSL 1.0.2 in this project so other projects can use it.

So DSC and OMI will also have to build with SSL 1.0.2, I already submitted PRs to DSC and OMI projects.

**Comment by jeffaco** [comment]
I still don't understand. This isn't a binary compatibility issue. Building against 1.0.0 is binary compatible with building against 1.0.2. So `ostc-openssl` should not be affected.

If the system already has `1.0.1f`, for example, on it, then what are you going to do? Reinstall OpenSSL? That would be a huge mistake, will likely break the system, and puts Microsoft in the owners seat for owning SSL distributions (something you're highly unlikely to get past security review).

You can build against OpenSSL 1.0.0, as is already happening, and then have an install-time dependency check to make sure that `1.0.2` is installed, if you need it for some sort of specific bug fix. But again, this is not a build issue, as OpenSSL 1.0.0 is binary compatible with OpenSSL 1.0.2.

If you don't understand what I'm saying, I suggest you schedule a brief meeting with me, or chat with someone else that understands. Or, if worse comes to worse, go to someone else for review. But I can't sign off on something that I think is fundamentally broken.

**Pull request closed without merging**
